### ISSUE TITLE
DB Schema Review

### ISSUE THREAD

**Issue by BCrawfordScott** [laurenchambers/PupBnB#1]
Excellent work!  A couple of suggestions:

- [x] Add hostId to a spot - the spots host should be a user that will have the power to approve booking requests.
-  Agreed that you can get away with keeping the reviews and ratings on the booking (add a rating column to the booking table).
- If, in the future, you want hosts to be reviewable as well, you'll need to add a reviews table, but that can be a bonus.

**Comment by laurenchambers** [comment]
Added hostId to a spot, and added a reviews table to the Bonus section!
